version: '2.23.0' 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  depends_on:
    - db
    
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DATABASE: micro-with-doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: intex123
    volumes:
      - .db:/var/lib/postgresql/data
    ports:
      - 54322:5432